### ISSUE TITLE
Datepicker not styled

### ISSUE THREAD

**Issue by allanldk** [TabBlazor/TabBlazor#104]
**First of all : Great and good looking work 👍**

I'm having a problem getting the Datepicker to render correctly (look at picture).

![image](https://user-images.githubusercontent.com/58115585/224550779-15718f14-689d-4d65-9778-458cefffc8f9.png)

**My solution setup:**

- index.html file like:  https://github.com/TabBlazor/TabBlazor.Templates/blob/master/TabBlazor.Templates.Wasm/wwwroot/index.html
- TabBlazor Nuget version tested 0.7.17-alpha and 0.7.16-alpha
- No own produced CSS files
- No Console Errors

**Can you please advise me?**

**Comment by skyeoh89** [comment]
Hi, you have to add stylesheet reference in _Host.cshtml (for Server) or index.html (for WebAssembly) as below: -

<link rel="stylesheet" href="<YourApplicationName>.styles.css" />

**Comment by nieprzecietny** [comment]
confirmed adding
`<link rel="stylesheet" href="<YourApplicationName>.styles.css" />`
resolves issue

**Comment by allanldk** [comment]
> Hi, you have to add stylesheet reference in _Host.cshtml (for Server) or index.html (for WebAssembly) as below: -
> 
> <link rel="stylesheet" href="<YourApplicationName>.styles.css" />

Yes it is working - Thanks alot
Sorry for the late reply.
