### ISSUE TITLE
Suggestion: Release the code for tabblazor.com

### ISSUE THREAD

**Issue by TEllegaard** [TabBlazor/TabBlazor#150]
First of all: TabBlazor looks like a great project! Thanks for all the effort you have put into it!

It would be a great help for us all you could release the code for tabblazor.com. Of course there is a lot of code presented at tabblazor.com, but a lot of them can't run perfectly because they are missing stylesheets and/or libraries.

Thanks :-)

**Comment by joadan** [comment]
Hi,

Thanks for the feedback.

Code for TabBlazor.com is in the repo, https://github.com/TabBlazor/TabBlazor/tree/master/docs
There is both a WASM version, (TabBlazor.com) and also the same as a blazor server version.

Just clone the repo and you should be able to run the docs locally.

Regards Joakim
