### ISSUE TITLE
TablerIcons from table sample missing

### ISSUE THREAD

**Issue by AmrRahmy** [TabBlazor/TabBlazor#90]
where is TablerIcons.Info_circle?
in,

error,
error CS0103: The name 'TablerIcons' does not exist in the current context

code from the samples at https://tabblazor.com/docs/tables,
@using TabBlazor;
...
@code{
...
private async Task ShowDialog( string title ) {
        await ModalService.ShowDialogAsync(new TabBlazor.Components.Modals.DialogOptions {
                CancelText = "",
                StatusColor = TablerColor.Primary,
                IconType = TablerIcons.Info_circle,
                MainText = title
        });
}
}

nuget,
nuget TabBlazor 0.7.10-alpha

_Imports.razor,
@using TabBlazor

Program.cs,
builder.Services.AddTabler();
builder.Services.AddTabBlazor();

_Layout.cshtml, at the end of Head tag
<link rel="stylesheet" href="_content/TabBlazor/css/tabblazor.min.css" />
<script src="_content/TabBlazor/js/tabblazor.js"></script>

**Comment by joadan** [comment]
Hello,

Please check https://tabblazor.com/docs/icons 
Icons are not included by default. Just create a static class and select/copy the icons from the Icon list.

**Comment by AmrRahmy** [comment]
Okay, it's a bit strange that there is a class for it in the samples, but I have to create a different class with a different name as to not conflict with the existing one, but it works, thanks.
